### ISSUE TITLE
Maintenance ?

### ISSUE THREAD

**Issue by frisch-raphael** [HanMoeHtet/typeorm-translatable#1]
Hey there.
Thanks for the great work on this package.
Was wondering if you were planning to update/maintain it somewhat ?

**Comment by HanMoeHtet** [comment]
Hi @frisch-raphael, no, I no longer plan on maintaining this package since I don't have enough time and this library is relatively tiny. So if you want to use this, check the source code and directly integrate it into your project or feel free to fork this.

**Comment by frisch-raphael** [comment]
Makes sense, thanks for your answer :)
